### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by tbroyer** [adam-p/markdown-here#108]
Markdown Here Chrome extension uses 1GB of RAM after my browser has been open for 6.5 hours. I have many tabs open (60 or so), but still.

![capture du 2013-10-08 15 29 46](https://f.cloud.github.com/assets/173813/1289276/c469c29a-301e-11e3-946b-4cfc20960cea.png)

**Comment by wackywendell** [comment]
I'm still getting a memory leak on Chrome, (version 51.0.2704.84 (64-bit), Arch Linux).
