### ISSUE TITLE
Prettify and Send button

### ISSUE THREAD

**Issue by lance-gray** [adam-p/markdown-here#110]
When you enable the "forgot-to-render" option, it shows a warning that your e-mail hasn't been prettified. It has two buttons **Back** and **Send**.

I think it should have more options in it

- **Cancel**/**Back** : Do nothing and close dialog box.
- **Prettify Now** : Apply Markdown formatting without sending, and then close dialog box.
- **Prettify and Send** : Apply Markdown formatting and send formatted e-mail.

**Edit**: An additional touch would be a *Remember my selection* checkbox.

**Comment by adam-p** [comment]
I'm going to close this request. For these reasons:

- I don't think prettify-and-send in a single step is preferable to prettify-check-send. 

- I don't think that the workflow of forgetting to render (or purposely not rendering) and then relying on hitting the "forgot-to-render" prompt is very good/desirable.

- I don't think it's onerous to render and then send as a normal workflow.

**Comment by Cathryne** [comment]
Allow one counter argument, please: Thunderbird's spell-checker has a "Check spelling before sending" option that one can switch off to avoid additional clicking to finally send a mail. I would find it very preferable, to also avoid clicking to prettify.

+1 for an option to prettify automatically *and* a 1-click solution when forgetting it to do it manually if said option is not used.
