### ISSUE TITLE
Try to colorize text

### ISSUE THREAD

**Issue by wapmorgan** [adam-p/markdown-here#178]
I want to highlight text with red color.
Tried:

``` html
<table>
    <tr>
        <td style="color: red">Foo</td>
    </tr>
</table>

<font color="red">Not supported</font>
<div style="color: red">asd</div>
<span style="color: red">asdasd</span>
```

Does not work.

**Comment by tachim** [comment]
Hi @adam-p -- is there any way to achieve this effect in a more concise way? I.e. with more brevity than having to explicitly write out `<span class="important">...</span>`
