### ISSUE TITLE
Add blacklist of URLs where hotkey is disabled

### ISSUE THREAD

**Issue by jmfayard** [adam-p/markdown-here#183]
Hello,

First I would like to thaks @adam-p and cie for this fantastic project
I love especially to put nicely formatted source code in my email :)

I've just run into an annoyance today:
In Google Drive, where markdown-here does not work (see #28), the standard shortcut of markdown-here (Ctrl-Alt-M) conflicts with the "Insert > Comment" feature. A feature that, when you use it, you want to use _only_ with a keyboard shortcut. 

Suggestion: disable markdown-here shortcut for this url since it doesn't work anyway
Probably it would be wise to have a file of URLs who have the similar problem

**Comment by adam-p** [comment]
Modified the issue title to better reflect what should be done.

A work-around (almost): You can change the MDH hotkey in the options.
