### ISSUE TITLE
Doesn't work with Firefox Electrolysis (Nightly)

### ISSUE THREAD

**Issue by adam-p** [adam-p/markdown-here#207]
I don't know any more than that yet.

**Comment by swrobel** [comment]
Also seeing this a lot: 
<img width="730" alt="screen shot 2015-07-28 at 7 14 35 pm" src="https://cloud.githubusercontent.com/assets/157270/8946243/ea77fe58-355c-11e5-9a53-122f1b633105.png">

**Comment by ExE-Boss** [comment]
The following error message is printed repeatedly when using electrolysis and debugging addons:
```
unsafe/forbidden CPOW usage                                     RemoteAddonsParent.jsm:872:2
unsafe/forbidden CPOW usage                                      markdown-here.js:80:4
unsafe/forbidden CPOW usage                                      markdown-here.js:79:9
unsafe/forbidden CPOW usage                                      markdown-here.js:86
```
See: https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Cross_Process_Object_Wrappers

**Comment by adam-p** [comment]
It's finally time to close this. A WebExtensions MDH has been released, which is compatible with Electrolysis.
https://addons.mozilla.org/en-US/firefox/addon/markdown-here/

See #433 for code changes.
