### ISSUE TITLE
Improve gmail signature detection

### ISSUE THREAD

**Issue by redders6600** [adam-p/markdown-here#219]
I was having a problem with markdown-here parsing my email signature as markdown, after looking at the source and old release notes I spotted that adding `-- ` before the signature excludes it from being rendered.

I added `-- ` before my signature and coloured it white, which works perfectly, but perhaps as a suggestion for improvement, you could use the fact that gmail adds the `gmail_signature` class to the div containing the signature as a way to exclude it?

**Comment by adam-p** [comment]
There is info about using the semi-standard `'-- '` in the [README](https://github.com/adam-p/markdown-here#notes-and-miscellaneous). I also just added that info to [Tips and Tricks](https://github.com/adam-p/markdown-here/wiki/Tips-and-Tricks#sigs) wiki page (and eventually I'll remove it from the README).

It doesn't make me happy to add a special case for Gmail when there is already a sort-of-standard thing that works everywhere, but... Gmail *is* super important. So we'll leave this open as a feature request. 

(Submit a PR! Sounds like you already dug into the code. And I get so few PRs... *sniff*...)

**Comment by redders6600** [comment]
Ok I'll try to submit a PR when I get a chance :)

**Comment by adam-p** [comment]
Closing this bug. We ended up deciding not to merge the PR. (I still appreciate the effort, though!)
