### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by anstosa** [adam-p/markdown-here#224]
The syntax highlighting stopped working a couple weeks ago and hasn't come back.

I'm primarily using it in Gmail.

Happy to help troubleshoot, just let me know what you need.

**Comment by nchammas** [comment]
This worked for me too. I had this issue for the longest time and didn't think to search for a solution until now.

Glad it was an easy fix! (And thank you @adam-p for making such an indispensable tool!)

**Comment by adam-p** [comment]
I have added this to the [Troubleshooting](https://github.com/adam-p/markdown-here/wiki/Troubleshooting#no-syntax-highlighting) wiki page. Of course, the real problem is that the CSS handling should be better, but for now...
