### ISSUE TITLE
"forgot-to-render" check not working in Thunderbird 31.2

### ISSUE THREAD

**Issue by orschiro** [adam-p/markdown-here#229]
Hi there,

I enabled the "forgot-to-render" check. However, I do not receive any notification on sending my messages in Thunderbird 31.2 on Arch Linux 64-bit.

Can the following errors be related to it?

![screenshot](https://cloud.githubusercontent.com/assets/170947/5122525/fcdc359e-70a1-11e4-8353-7a3118a0aad4.png)

Thanks for your help!

Robert

**Comment by adam-p** [comment]
Can I close this issue? Can I infer from #234 that sometimes forgot-to-render works correctly?

**Comment by orschiro** [comment]
@adam-p 

Yes, please close it for now. I can live without a correctly functioning check, especially given that I am the only person with that very misbehaving Thunderbird. :P
