### ISSUE TITLE
rendering changes font of normal text

### ISSUE THREAD

**Issue by Agrisolum** [adam-p/markdown-here#230]
In gmail I have verdana set up as my default font.  When I render, the font is changed to sans serif.

Also when I un-render, a new line is always added at the very beginning of my mail.

**Comment by orschiro** [comment]
Sometimes I face the same issue in Thunderbird. 

**Example of an email that is initially displayed correctly:**

![screenshot](https://cloud.githubusercontent.com/assets/170947/5695187/6ed45412-9995-11e4-9411-51c6ce12a2a5.png)

**However, rendering changes the font type to an undesired one:**

![image](https://cloud.githubusercontent.com/assets/170947/5695190/813b35bc-9995-11e4-9b08-cb0fa18ed28c.png)

**In contrary, this example will render fine:**

![image](https://cloud.githubusercontent.com/assets/170947/5695194/9afd490e-9995-11e4-920d-81b0f06d5c2e.png)

**The result uses the desired font type:**

![image](https://cloud.githubusercontent.com/assets/170947/5695195/a52d897a-9995-11e4-9017-4bda405738eb.png)

**Comment by adam-p** [comment]
@Agrisolum: [I figured out](https://github.com/adam-p/markdown-here/issues/236#issuecomment-67788519) that the reason you're getting blank lines is because you use a custom font in Gmail.  This is captured in #236, so I'm going to close this issue.

@orschiro: You sure get the weirdest bugs. Do you use a custom font in Tbird?

**Comment by orschiro** [comment]
@adam-p 

Yes I do use a custom font. They are not supported?

![image](https://cloud.githubusercontent.com/assets/170947/6570699/35801d9e-c6ff-11e4-96d8-eb32f17927c7.png)

**Comment by adam-p** [comment]
@orschiro: Custom fonts interact badly with MDH in Gmail webmail (#88) and in Thunderbird as well.
I just opened a new issue to track this: #264
