### ISSUE TITLE
Support inline math

### ISSUE THREAD

**Issue by adam-p** [adam-p/markdown-here#231]
As requested [here](https://groups.google.com/forum/#!topic/markdown-here/xoK4WD5Nz5s).

**Comment by adam-p** [comment]
There *is* support for inline math. (And was at the time this issue was created.) So... Maybe the original request was for *block* math? 

Anyway, closing.

**Comment by ickc** [comment]
That link mentioned inline Math *and* Display Math.

So this issue probably should be reopened and renamed as "Support Display Math".

**Comment by cben** [comment]
The default depends on image rendering service, but you can override it by starting the formula with things like `\displaystyle` or `\textstyle`:
https://tex.stackexchange.com/questions/32824/show-inline-math-as-if-it-were-display-math
- CodeCogs defaults to display and seems to encourage non-standard `\inline` for inline.
