### ISSUE TITLE
Not doing anything in Gmail

### ISSUE THREAD

**Issue by christianbundy** [adam-p/markdown-here#238]
![screen shot 2015-01-20 at 4 20 38 pm](https://cloud.githubusercontent.com/assets/537700/5828992/50050004-a0c0-11e4-80b0-4a0e869b9f0e.png)

Selecting the text, right-clicking, and clicking "Markdown Toggle" doesn't do anything at all. How can I troubleshoot?

Thanks!

**Comment by therealmarv** [comment]
Reload the page before the first usage. I had similar issue when using it right now ;)

**Comment by adam-p** [comment]
Did reloading the page fix it? Can I close this issue?

**Comment by adam-p** [comment]
Closing this issue. You can re-open it if there's more info. (Doing issue clean-up.)
