### ISSUE TITLE
'forgot-to-render' issue

### ISSUE THREAD

**Issue by jwarkentin** [adam-p/markdown-here#239]
I love having this feature, but I often seem to get the 'forgot-to-render' message when I click the send button even though I have rendered already (in both the gmail and inbox interfaces). While I haven't paid enough attention in the past, could it possibly be caused by making edits after toggling the markdown? With an email I just sent I had it render the markdown, then I made a couple tweaks and sent it and I got the alert.

**Comment by r2evans** [comment]
I saw something similar, and it usually happens after I render and then edit the text. Does the "forget-to-render" message happen due to "I think the source is in markdown" and "the most recent action was not to render" (regardless of actual rendered state)?

**Comment by adam-p** [comment]
You can find out what triggered the forgot-to-render by bringing up the browser console for the page (F12 or Alt+Cmd+J). The last message you see there will be Markdown Here reporting what caused it to think there was unrendered Markdown in the email.

I plan on re-working the feature (probably after switching Markdown libraries). I'm going to make issue #159 the catch-all for "make forgot-to-render better". ...So I'm going to close this one. But it would still be good to know what's triggering the prompt for you -- let me know in #159.
