### ISSUE TITLE
Add checklist support

### ISSUE THREAD

**Issue by npassaro** [adam-p/markdown-here#242]
Recently github as added a support for checklist as this one:
- [ ] this is the code below
```
- [ ] this is the code below
```

Are thinking of adding something like this? 
It would be cool as even Evernote uses this type of checklists and it is the missing link to be able to use this as my evernote editor :smiley:

**Comment by adam-p** [comment]
I hadn't seen this bug when I created #259, which is the same thing. I'm going to close this issue and keep that one. But you won't be forgotten!

**Comment by npassaro** [comment]
:+1:

**Comment by swiesmann** [comment]
:+1:

**Comment by chabad360** [comment]
:+1:
