### ISSUE TITLE
Chrome plugin inserts an additional blank line at the top of Gmail

### ISSUE THREAD

**Issue by JamesMcMahon** [adam-p/markdown-here#243]
When using the current Chrome plugin (2.11.3) toggling Mardown mode in a Gmail will insert a space at the top of the email. It effectively looks like an additional line of whitespace, but this line is not removable.

Here is an example, before:
![screen shot 2015-02-02 at 5 26 44 pm](https://cloud.githubusercontent.com/assets/916676/6010498/f306ab3c-ab00-11e4-8d13-177d9949d482.png)

After:
![screen shot 2015-02-02 at 5 26 59 pm](https://cloud.githubusercontent.com/assets/916676/6010499/f4f2cd72-ab00-11e4-856e-5d42bcdd8917.png)

This is on Chrome 40.0.2214.94 on Mac OS X (10.10.2).

Let me know if any more information is needed.

**Comment by adam-p** [comment]
I have noticed this, but I guess I stopped seeing it after a while. I'll fix it in the next release.

You can fix it yourself by adding this to your "Primary Styling CSS" in the MDH Options, *below* the existing `p` rule (so, it's fine if you just add it to the bottom):

```css
.markdown-here-wrapper:first-of-type > p:first-of-type {
  margin-top: 0 !important; 
}
```

(I adapted that from the [Salutation Styling](https://github.com/adam-p/markdown-here/wiki/Tips-and-Tricks#salutation-styling) on our Hints and Tips wiki page.)

Does that fix it for you?

**Comment by JamesMcMahon** [comment]
That fix does work, thanks!

Is that something that can be fixed for everyone in future versions of the plugin?

**Comment by adam-p** [comment]
Yes. I think it's an improvement, so I'll add it to the default CSS in the next release. (Unfortunately, people will have to reset their CSS to get the change. Blah. Dumb design. #48, #78.)

**Comment by adam-p** [comment]
In my fix I made an even simpler change -- I just got rid of the top margin altogether. The `<p>` rule is now:

```css
p {
  margin: 0 0 1.2em 0 !important;
}
```

(Also note that in the CSS I suggested earlier, the `.markdown-here-wrapper:first-of-type` is meaningless -- `:first-of-type` [can't be used with classes](https://stackoverflow.com/questions/2717480/css-selector-for-first-element-with-class/8539107#8539107).)
