### ISSUE TITLE
Markdown Here does not format as advertised in Chrome/Safari gmail/aol mail on Mac

### ISSUE THREAD

**Issue by wizardwerdna** [adam-p/markdown-here#255]
My installation of MDH fails in various ways that are inconsistent with the documentation.

1. Tables

Tables in GMD format are not being formatted at all.

1. Lists

Ordered sublists all use arabic numbers, rather than going to roman numbers.

I can't figure out why installation is failing when others seem to have things working.  Any hints?

**Comment by adam-p** [comment]
I don't have a Mac to test on right now, but...

First of all: Let's start by talking about Chrome and not Safari -- I haven't done a fresh Safari release in a while, so it has fallen behind a little.

Secondly, restart your browser after install MDH.

Thirdly, check the "Preview" on the Markdown Here options page. What you see there is what you should get in Gmail.

Fourthly, can you provide the original Markdown you're trying to use and a screenshot of the result?

Tables: Are you pasting them or typing them? Tables are very sensitive to newlines and can mess up with pasting.

Lists: By default it uses the default HTML/CSS numbering scheme, which is Arabic numerals. If you want Roman numerals, add this style to your MDH "Primary Styling CSS":

```css
ol {
  list-style-type: upper-roman;
}
```

**Comment by wizardwerdna** [comment]
Thanks, Adam, for your feedback.  I cut and pasted the sample code in the
Options page and it worked correctly.  I retyped my examples and messed
with the line endings and eventually got it to work.

As to the counting, I was relying on the examples in your cheat sheet,
which rendered:

1. foo
  1. bar
  1. baz

as:

1. foo
  i. bar
  ii. baz

of course i can accomplish that effect with a style sheet, and that will be
my plan.  I do, however, suggest that you use the same stylesheets for your
cheat sheet as you do for your default sheets.

Great work, and I'm glad to be up and running.  I'll wager Safari will
behave properly as well, now that I "see the light."

**Comment by adam-p** [comment]
Now I see what you mean...

> I do, however, suggest that you use the same stylesheets for your cheat sheet as you do for your default sheets.

The cheatsheet styling relies on the styling Github provides (it's a Github wiki page), and is independent from the MDH styling. I *could* take screenshots of the examples, and embed them in wiki, so they're exactly accurate, but... I'm not going to. Or I *could* host the cheatsheet elsewhere, on a page where I control the styling, but... it's too late for that -- the cheatsheet already has a ton of links to it.

So styling deviations from the cheatsheet are always going to happen, as Github and MDH diverge here and there.

That being said... I really like the new Github sub-list styling, so I'm going to steal it and make it the default in Markdown Here. In the next release I'll be adding these styles:

```css
ol ol,
ul ol {
  list-style-type: lower-roman;
}

ul ul ol,
ul ol ol,
ol ul ol,
ol ol ol {
  list-style-type: lower-alpha;
}
```

This sounds like it's resolved. Closing it.
