### ISSUE TITLE
markdown here always warns about the document being markdown, but not enabled

### ISSUE THREAD

**Issue by tkelley65** [adam-p/markdown-here#257]
It is impossible to tell whether it is off or on. I've sent several markdown emails in plain text because of this. It always give the warning about being markdown but not enabled not matter how it is toggled. A toggle with no indicator is a terrible idea - it needs an on/off switch. As a result I never trust it when I am sending mail and well, have stopped trying to use it.

**Comment by adam-p** [comment]
I don't understand. 

> It always give the warning about being markdown but not enabled not matter how it is toggled.

So, you're getting the "did you forget to render" prompt? But... what's not enabled? The Markdown Here button?

What client are you using (Chrome, Firefox, Thunderbird, etc.)? What email service (Gmail, etc.)?

> A toggle with no indicator is a terrible idea - it needs an on/off switch.

Generally speaking, I agree that toggle switches are inferior. There's a complication with Markdown Here, though: the email is not necessarily only unrendered or rendered. If some of the email is selected when the button is pushed, only that part is rendered -- and then the email will be partly rendered and partly unrendered. And then what the button does next will differ depending on where the cursor is.

So, Markdown Here would have to keep monitoring the location of the cursor, the current selection, and the state of the text around the cursor. Not insurmountable, but more work and processing time.

Another complication: Chrome only lets you have a single toolbar button, and you can't change the icon -- you can only enable disable. (IIRC.) 

I, personally, don't have trouble with toggle. For example, when I first created the extension, there was no button at all -- only a context menu item and a hotkey. And I still only use the hotkey. I don't have a trouble with remembering the state. But, yes, that's just me.

Anyway. I'd appreciate if you can answer the question at the top. I created a new issue for changing how the toggle button is displayed: #258.

**Comment by adam-p** [comment]
I'm closing this issue, as your comment in #244 is that it's resolved for you.
