### ISSUE TITLE
Make toggle button more state-aware

### ISSUE THREAD

**Issue by adam-p** [adam-p/markdown-here#258]
Right now the button is only enabled if focus is in a valid render target, or disabled if it isn't. But it could also indicate whether clicking it would result in a render or an unrender taking place. 

(On Chrome maybe a [`browserAction` badge](https://developer.chrome.com/extensions/browserAction#badge) can be used.)

**Comment by tmr232** [comment]
That would be great.
Maybe also an overlay icon in the edited area itself?

**Comment by adam-p** [comment]
I'm closing this issue. I don't think it's an important enough feature to warrant the additional complexity.

**Comment by escapewindow** [comment]
This is a great addon! My only gripe is I keep editing the html thinking it's markdown, then I get the warning and unrender when I try to convert it to html. I would love a visual indicator like this, at least in the toolbar.
