### ISSUE TITLE
"forgot-to-render" popup is really annoying

### ISSUE THREAD

**Issue by jmfayard** [adam-p/markdown-here#265]
Hello, 

I love markdown-here but thing that having implemented this "forgot-to-render" check is really a bad idea, except if the purpose was to get immediate feedback on how to get it done in a sane way.

Why is it a bad idea?

Well, the essence of markdown is his simplicity. 
It started cleverly from an observation on how people sponatnously formatted their plain-text email.
That was really ``**clever**``
Oh, why not display this nicely? Just continue to write how you already did it and we take care of displaying it nicely.
Another cool thing about markdown, is that totally unformatted text is correct markdown. (Not the cas with html :)

You broke this by bothering me with a popup when I am sending this damn email that needs to be send right now, even if I really do not care about formatting nicely my two-lines long urgent email.
Github issues also support markdown. 
Would you like if it asked you every time you enter a simple comment ?

Ok, time for suggestions on how to make things sane again if we want to poursue your idea.
One possibility is of course to have "forget-to-render" unchecked by default, but we can do better.

- check if I'm using non-trivial markdown syntax. If I put ``[google](http://google.fr)``` I probably **mean** I want to enter markdown here
- If there is no non-trivial markdown syntax, don't do anything
- if there is some, assume I want to use markdown-here, but give me chance to cancel the formatting. If I cancel, send the email immediatly with no formatting done. If I don't, send the email with formatting after 3 seconds

**Comment by adam-p** [comment]
The ["is this Markdown" checks](https://github.com/adam-p/markdown-here/blob/6af68808439f1a98c501af8e427e0bf095df9c1b/src/common/common-logic.js#L310) are supposed to only detect non-trivial MD. But it is also probably impossible to hit the perfect balance for all users. You are correct that it should have been off-by-default until it was more configurable. 

There is an issue tracking forgot-to-render improvements: #159 

As for getting rid of it: I want the feature for myself, and others also requested it. Disabling it is not onerous.
