### ISSUE TITLE
Problem with the new release and Firefox 

### ISSUE THREAD

**Issue by georgejean** [adam-p/markdown-here#277]
Thanks for this very useful plugin.

Nevertheless, since the new release (21 May 2015), I can't get anymore the render of the Markdown's code in my email (gmail). Instead, the text is selected and nothing happens.

Thanks for any suggestions.

**Comment by adam-p** [comment]
I just tried it out and didn't have a problem. Let's investigate...

1. Have you tried restarting the browser?

2. Are you running the Firefox "Developer Edition" (v40.x)? If so, Markdown Here will only work in a "non-e10s window".

3. Does the MDH Options page work/render?

4. Do you see any errors in the tab or browser consoles?

**Comment by georgejean** [comment]
It's strange. Now, I don't know why, but there isn't actually any problem!! Thanks for your response.

1. Yes, I tried to uninstall and reinstall the plugin. The problem was still here.
2. No.
3. I tried it but it didn't work.
4. No (and I haven't investigated in this direction)

Problem is solved.

**Comment by adam-p** [comment]
I don't think the problem is actually solved. Main issue for this is now #278.

**Comment by georgejean** [comment]
Great! Thanks.
