### ISSUE TITLE
Markdown Here not working at all in Firefox Linux (latest)

### ISSUE THREAD

**Issue by fardog** [adam-p/markdown-here#278]
When running Markdown Here (v2.11.8) in Firefox (v38.0.1), text is never converted (even on the "Preview" section of the Markdown Here preferences!). When clicking the toolbar button, or using the keyboard shortcut, all text in the textbox is selected, but no conversion is performed. This has been an on-and-off issue with Markdown Here for some time, I've just now taken the time to report it (sorry!).

I've tried the following:

- Uninstall and reinstall add-on
- Run only the markdown here add-on by itself
- Reset all settings to default in the add-on (at least using any "reset to default" buttons I could find)

Unfortunately nothing has resolved. When I run the web console, I don't see any output or error messages, so I'm not sure how to give you any better information. Please let me know what I can provide that'll help resolve the problem!

It's worth noting that on the same machine, Markdown Here works fine in Chromium. This is on Arch Linux, running all the latest packages.

Thanks!

**Comment by fugo** [comment]
This happends to me in *Thunderbird 31.7.0 Linuxmint 17.1 32bit* also.
Older versions working very well. I installed now **2.11.7** so I can use it.

**Comment by adam-p** [comment]
I'm pretty sure I found the problem. Fixed in df84634. I have just put out a new release (only for Firefox and Thunderbird), but it might take some time to pass review (because it usually does). You can grab the pre-approved version here:
https://addons.mozilla.org/en-US/firefox/addon/markdown-here/versions/?page=1#version-2.11.9

And, of course, re-open this issue if the problem isn't fixed.

**Comment by fugo** [comment]
## Thank you a lot
You are realy fast :) - now it works with this new version.

**Comment by adam-p** [comment]
The new version has been approved by Mozilla.

**Comment by fardog** [comment]
yes, thanks so much! the new version fixed it!
