### ISSUE TITLE
Quote selected text in Gmail

### ISSUE THREAD

**Issue by orschiro** [adam-p/markdown-here#280]
Dear @adam-p,

Would it be possible to add an option that automatically adds selected text in a Gmail conversation as quoted markdown code (`>`) into an reply?

Thankfully,

Robert

**Comment by adam-p** [comment]
It's an interesting idea, but it really sounds like that would make more sense as a separate extension. "Paste as quoted text" or something.

So... I'm going to close this.

**Comment by orschiro** [comment]
Hi @adam-p,

I appreciate your quick response. There is a Gmail lab feature called `Quote selected text`. 

However, it does not quote the text as markdown-compatible code (`>`). Therefore I was raising the issue here.

**Comment by adam-p** [comment]
I hear you. I just think that it's too different from what Markdown Here does, and it would probably be better a new extension. (And if you just want to target Chrome, then creating an extension is super easy. Firefox is a pain. Cross-platform even more so.)

**Comment by orschiro** [comment]
Thanks very much Adam!

I will see what I can do myself.

Robert

On Wednesday, May 27, 2015, Adam Pritchard <notifications@github.com> wrote:

> I hear you. I just think that it's too different from what Markdown Here
> does, and it would probably be better a new extension. (And if you just
> want to target Chrome, then creating an extension is super easy. Firefox is
> a pain. Cross-platform even more so.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adam-p/markdown-here/issues/280#issuecomment-105878831>
> .
>


-- 

mindfully present. just be and let go.

passionate. simple life. user-centred design.

impulsive thinking. human hearted.

Co-Creator of @MindfulMeerkats <https://twitter.com/MindfulMeerkat>.

Website: robert.orzanna.de

Twitter: @orschiro <https://twitter.com/orschiro>
