### ISSUE TITLE
Google inbox: No warning for detected markdown code

### ISSUE THREAD

**Issue by therealmarv** [adam-p/markdown-here#283]
In Gmail I get a warning when I type Markdown code and want to send that email.

Nowadays I switched to inbox and today I've send an email with Markdown code and forgot to convert it.

Would be helpful to have a warning also there (btw. sometimes the warning is wrong).

**Comment by adam-p** [comment]
It broke due to change in the Google Inbox markup. Fixed in rev d003a96.

**Comment by therealmarv** [comment]
wow, thanks :)
