### ISSUE TITLE
Transparent icon for markdown-here 

### ISSUE THREAD

**Issue by KwenString** [adam-p/markdown-here#290]
current icon looks ugly since the border and white bg
why don't you set just like below:
( I change the icon by pixlr editor )

**Comment by KwenString** [comment]
![image](https://cloud.githubusercontent.com/assets/4601005/8395170/14dcc2dc-1d93-11e5-847d-b20bff179d41.png)

**Comment by adam-p** [comment]
We are currently working on [an entirely new logo](http://markdown-here.com/logo.html), which will have a transparent background. 

I'm going to close this issue.
