### ISSUE TITLE
How to apply strikethrough within code segment

### ISSUE THREAD

**Issue by abdullahyildiz** [adam-p/markdown-here#291]
Is it possible to apply strikethrough within a code segment?

**Comment by adam-p** [comment]
Nope. MD isn't processed inside code. For example:

    ~~strikethrough~~
    
    `~~strikethrough~~`
    
    ```
    ~~strikethrough~~
    ```


~~strikethrough~~

`~~strikethrough~~`

```
~~strikethrough~~
```

**Comment by g-u-r-k-a-n** [comment]
I know the post is pretty old but I just wanted to say that I found this usage, even if it's a bit of a troublesome use. :satisfied:

<pre><code><del>void Foo(string[] args){</del>
   <del>foreach(var arg in args)</del>
<del>}</del>
</pre></code>

[strikethrough code in markdown on github](https://stackoverflow.com/questions/41395000/strikethrough-code-in-markdown-on-github)

**Comment by fmichaut-dev** [comment]
@g-u-r-k-a-n Can you show how you did it ?
I tried everything on your link, but nothing gave the same result

**Comment by g-u-r-k-a-n** [comment]
@fmichaut-dev Sure. You should use `del` tag in the `pre` and `code` tags

<pre><code><del>void Foo(string[] args){</del>
   <del>foreach(var arg in args)</del>
<del>}</del>
</pre></code>

![image](https://user-images.githubusercontent.com/55924924/146539657-5a055c93-53b0-403a-b857-b6badac20aff.png)
