### ISSUE TITLE
Options page needs a overhaul

### ISSUE THREAD

**Issue by pradyunsg** [adam-p/markdown-here#292]
Firstly, Awesome Plugin!!!
I've had it for less than 2 hours and it's already feeling awesome! The first time I tested it, I thought "Wow! Awesome stuff!".

~~With the new logo coming up,~~ (it came out) It would be nice if options.html page also got a re-visit and got revamped. There quite a few things there that deserve changing. For one it doesn't look very nice and it really is functionally flawed (doesn't work as well as it can), but it does work.

PS: I'm willing to do this, over this weekend. Just wanting to see if there's anyone other than me who thinks it's worth the time and effort.

10-Sept-2015: Strikeout new-logo related text.

**Comment by adam-p** [comment]
One of the logo contributors has started to do some work on the options page. I'll point him toward this issue in case he want to collaborate with you.

**Comment by pradyunsg** [comment]
Sure!

**Comment by pradyunsg** [comment]
Sure! 
Please keep me posted on this...

**Comment by rafegoldberg** [comment]
Hey @pradyunsg I was also hoping for a redesign the MdH options page. I've been quite busy with client work recently (hence the delay!) but have integrated Grunt and gotten somewhat started on this. Let me know what you're thoughts are. My intention was to simplify the layout using a BEM/SMACCS SCSS approach alongside a simplification of the HTML. Let me know what you're thinking!

**Comment by pradyunsg** [comment]
I was thinking stealing the design from the new Preferences page in Firefox. I had this in mind:
- General tab
  will contain the basic instructions, what is currently in "Basic Usage", "Resource and Links" and "Contributing" and footer.
- Customize/Settings tab
  For "Advanced and Miscellaneous", Hotkey and the CSS, along with hopefully, some compilation backend allowing for use of SCSS and the likes. :smile:
- Donate tab
  Because, donations are important.

**Comment by pradyunsg** [comment]
Does anyone mind if the page uses JQuery and Bootstrap? Because, that'll make life easier.

**Comment by pradyunsg** [comment]
@rafegoldberg Hi! Check out #294, I did a little something...

**Comment by adam-p** [comment]
`options-tab-about.html` and `jquery-2.1.4.js` are missing or mislocated in the PR.

**Comment by pradyunsg** [comment]
Meh.
