### ISSUE TITLE
[Feature] support for github smileys

### ISSUE THREAD

**Issue by Redsandro** [adam-p/markdown-here#348]
Could we add support for all the github smileys?  
http://www.emoji-cheat-sheet.com/

Not sure how the markdown is parsed internally, but here's a plugin for mark-it-down:  
https://github.com/markdown-it/markdown-it-emoji

**Comment by Redsandro** [comment]
There seem to be some possible duplicates:

* https://github.com/adam-p/markdown-here/issues/101
* https://github.com/adam-p/markdown-here/issues/355

**Comment by pradyunsg** [comment]
Close this one then?
