### ISSUE TITLE
some errors in python

### ISSUE THREAD

**Issue by pierre94** [adam-p/markdown-here#351]
hello,the comments in python are start with "#".So if my python codes contain some comments,there will be some errors.
My codes like this:

``` python
# hello world!
```

**Comment by algorythmic** [comment]
Put your code inside a [code block](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)?

**Comment by ErichDonGubler** [comment]
@pierre94 The sample you posted looks correct...

**Comment by pierre94** [comment]
@ErichDonGubler  "#" is explained with markdown  not python .

**Comment by cclauss** [comment]
Can this issue be closed?

**Comment by pierre94** [comment]
> Can this issue be closed?

Yes!
I can use it successfully now.
