### ISSUE TITLE
Cannot generate the table

### ISSUE THREAD

**Issue by nguyennb9** [adam-p/markdown-here#358]
This markdown to gennerate a table doesn't work

```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

It should look like this

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

But this is the output:
`| Tables        | Are           | Cool  | | ——————- |:——————-:| ——-:| | col 3 is      | right-aligned | $1600 | | col 2 is      | centered      |   $12 | | zebra stripes | are neat      |    $1 |`

Even when I try it in official `Markdown Here` page `chrome-extension://elifhakcjgalahccnjkneoccemfahfoa/common/options.html`
![image](https://cloud.githubusercontent.com/assets/12994001/15207650/a3466c12-1851-11e6-98b5-f2398b47b113.png)

**Comment by duckbrain** [comment]
You're markdown isn't parsing in Github either. I think you have em dashes instead of hyphens. I replaced the dashes and the table formats fine in Github and on the Markdown here website. My guess is that it was copied and pasted from Word or some other word processor. :wink:

| Tables | Are | Cool |
|----------|:----------:| -------:|
| col 3 is | right-aligned | $1600 |
| col 2 is | centered | $12 |
| zebra stripes | are neat | $1 |

**Comment by nguyennb9** [comment]
In my case, I copy that table from [markdown cheat seat](https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet) and paste in Evernote.

Btw, I can parse it in Github without change anything

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

Hmm, something wrong?

**Comment by duckbrain** [comment]
Okay, my mistake. I was parsing your output as your input. 

`| Tables | Are | Cool | | ——————- |:——————-:| ——-:| | col 3 is | right-aligned | $1600 | | col 2 is | centered | $12 | | zebra stripes | are neat | $1 |`

I just tried in Evernote. It looks like when you paste it is going in formatted with the styles on the markdown cheat sheet. It detecting that as already formatted markup is toggling the Markdown off, which results in the code it gives you. If you toggle that thing again, it gives you your normal code. In Chrome, if you Ctrl+Shift+V to paste, it will paste without formatting. Then the Markdown toggle works correctly.

**Comment by nguyennb9** [comment]
It works like a charm. Thank you!
