### ISSUE TITLE
Textarea support

### ISSUE THREAD

**Issue by Iristyle** [adam-p/markdown-here#36]
Came across this and was impressed... pretty awesome.

There are a few other cases where this would be even more useful -- within standard `<textarea>`.
- Forums like phpBB or vBulletin that want BBCode (BBCode **sucks** compared to Markdown)
- Craigslist thats OK with HTML
- Other textarea based sites

So I'm not sure the best approach -- could overlay the existing textarea with a `contenteditable` div... or mod the DOM to add the attribute to the `textarea` -- which probably has side effects.

Just thought I'd throw it out there -- this would increase the utility of this extension quite a bit IMHO.

Thanks for the consideration!

**Comment by timofonic** [comment]
@adam-p Sorry for replying an old message.

Why would be outside the domain of the extension? I don't get it, sorry.

What's so radically difficult about a `textarea`? Would you like to explain it? Why is it outside the scope/domain of Markdown  Here? Please :D
