### ISSUE TITLE
Checkbox support

### ISSUE THREAD

**Issue by diazgilberto** [adam-p/markdown-here#375]
Do the extension supports [ x ]?

**Comment by jrappen** [comment]
| 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |
|---|---|---|---|---|---|---|---|---|
| BOL | optional whitespace | `*` | space | `[` | space or x | `]` | space | text |

**Comment by mayanez** [comment]
This doesn't work for me. Do I need to add anything to the styling CSS?

**Comment by FengZhiheng** [comment]
This doesn't work for me, too. By the way, what's the meaning of "BOL".
