### ISSUE TITLE
Option can't be used in Firefox .

### ISSUE THREAD

**Issue by happyconfident** [adam-p/markdown-here#385]
When you installed a Markdown Here in Firefox , you clicked the option from the Markdown Here and you would find the Firefox didn't work.

**Comment by juaalta** [comment]
The same happens to me.
If I access the configuration from the URL directly, I get misconfigured and modify these options are not updated.
I used the next url: `resource: //markdown_here_common/options.html`
Firefox 49.0
Markdown Here: 2.12.0

**Comment by juaalta** [comment]
I disabled the multithreading and does work.
It stopped working when activated multithreading.

**Comment by haililihai** [comment]
I got the same issue in Firefox 50.0.1 (Linux & Win).
In Linux, when the "preferences" button is clicked, noting happen. While in Windows 7, when the "options" button is clicked, the Firefox is totally stuck! Just kill-and-restart works.

**Comment by veevax** [comment]
Same issue, here. I tried to disable multi-threading but it didn't do the trick.
Anyone had more luck?

**Comment by adam-p** [comment]
Duplicate of #369 (which will be fixed soon).
