### ISSUE TITLE
Can organization admins add new skills to the system?

### ISSUE THREAD

**Issue by mjmilan** [adam-p/markdown-here#405]
Can an organization admin add new skills to the system, and if not, should they be able to? 

As new organizations come to use the system, they will want skills to be available that are relevant to the particular domains they work under. So, someone fitting a smoke alarm for example could, conceivably, have a skill of "Ladder Operation".

I am unable to confirm this directly as I cannot verify a new account to use as an organization admin.

If organization admins can add new skills directly, then I would suggest this issue be abandoned.

@billwagner, @oohmcgoo

**Comment by BillWagner** [comment]
Tagging @ohmcgoo and @tonysurma for guidance here.

**Comment by mjmilan** [comment]
My apologies Adam-p - I have two different projects open on Github and I have unfortunately raised some issues against your system that were intended for htbox/allready. 

My apologies - they'll drag me out the building and throw me in the Thames momentarily!

Martin.
