### ISSUE TITLE
Support kotlin highlight?

### ISSUE THREAD

**Issue by enbandari** [adam-p/markdown-here#408]
Kotlin is a Jvm language by Jetbrains. Would it be supported?

**Comment by jrappen** [comment]
Using the following file:

<https://github.com/isagalaev/highlight.js/blob/master/src/languages/kotlin.js>

when updating the included version of `highlight.js` here:

<https://github.com/adam-p/markdown-here/blob/master/src/common/highlightjs/highlight.js>

should do the trick. Included languages can be selected using the download generator from:

<https://highlightjs.org/download/>

**Comment by jrappen** [comment]
PR #403 fixes this issue.

**Comment by shenguojun** [comment]
Kotlin seems not working in the current version, checked https://github.com/adam-p/markdown-here/blob/master/src/common/highlightjs/highlight.js and cannot find registerLanguage for Kotlin also.  Is there some else needed to do to support Kotlin?

**Comment by shenguojun** [comment]
@jrappen I have tried to add kotlin highlight function to  https://github.com/adam-p/markdown-here/blob/master/src/common/highlightjs/highlight.js and add chrome extension from the src/ directory, but still don't work. Can you give me some help?

**Comment by shenguojun** [comment]
Finally I have solved these problem. For people need kotlin heighlight & weixin open platform style support can use the code here https://github.com/shenguojun/markdown-here
