### ISSUE TITLE
Simple issue: combined emphasis doesn't render what is says (cheatsheet)

### ISSUE THREAD

**Issue by gabrielprioli** [adam-p/markdown-here#409]
In the Emphasis section

```Emphasis, aka italics, with *asterisks* or _underscores_.```
> Emphasis, aka italics, with *asterisks* or _underscores_.

OK

```Strong emphasis, aka bold, with **asterisks** or __underscores__.```
> Strong emphasis, aka bold, with **asterisks** or __underscores__.

OK

```Combined emphasis with **asterisks and _underscores_**.```
> Combined emphasis with **asterisks and _underscores_**.

Not ok: renders strong emphasis on "asterisks and" and combined emphasis on "underscores"

The code that renders correctly is:

```Combined emphasis with **_asterisks and underscores_**.```
> Combined emphasis with **_asterisks and underscores_**.

**Comment by RMDavidson** [comment]
Actually, I'm not sure any of these are rendered correctly as I don't see an actual underscore anywhere in these examples.

**Comment by AvgustPol** [comment]
> Actually, I'm not sure any of these are rendered correctly as I don't see an actual underscore anywhere in these examples.

As i can see you can use "underscore" before and after the word to make it bold or italic 

![image](https://user-images.githubusercontent.com/29002229/53757037-e9458f80-3eba-11e9-8463-c26d4d5d5504.png)

**Comment by gabrielprioli** [comment]
@adam-p can reopen if he thinks this is relevant.
