### ISSUE TITLE
Add an order to change the font size.

### ISSUE THREAD

**Issue by JaoChaos** [adam-p/markdown-here#418]
In markdown language, when you finish the document the font size of all the document uses to be really big in comparision with others.
Please, try to fix this, and add an order to write at the top of the document that changes the font size of all the document or a particular section, because sometimes isnt beautiful having a good document with oversized font.

Thanks for your attention.

**Comment by adam-p** [comment]
You can modify your font size in the "Primary Styling CSS" in the Markdown Here options. For example:

```
.markdown-here-wrapper {
  font-size: 0.5em;
}
```

I'm closing this issue. Re-open it if there's more to it.
