### ISSUE TITLE
WebExtensions can be installed in Thunderbird (they just currently don't work)

### ISSUE THREAD

**Issue by ExE-Boss** [adam-p/markdown-here#423]
I've managed to successfully install two of my WebExtensions in Thunderbird, and the options page does show up correctly (but doesn't actually change anything).

The issue is that Thunderbird doesn't have any of the required WebExtension APIs implemented, and as such the WebExtensions don't work at all.

But because of the fact that they are recognized as WebExtensions and the description and options page show up correctly, I suspect that Thunderbird will eventually implement the required WebExtension APIs.

---

#### Firefox:
[ExE Boss’s Extension Suite](https://addons.mozilla.org/en-US/firefox/collections/ExE_Boss/extension-suite/):
- [Firefox about:about Button](https://addons.mozilla.org/en-US/firefox/addon/firefox-about-button)
- [View Image in New Tab](https://addons.mozilla.org/en-US/firefox/addon/new-tab-image_exe-boss)

#### Thunderbird:
[ExE Boss’s Extension Suite](https://addons.mozilla.org/en-US/thunderbird/collections/ExE_Boss/extension-suite/):
- [Firefox about:about Button](https://addons.mozilla.org/en-US/thunderbird/addon/firefox-about-button)
- [View Image in New Tab](https://addons.mozilla.org/en-US/thunderbird/addon/new-tab-image_exe-boss)

---

P.S.: I'm setting up this issue to track when Thunderbird implements the required WebExtension APIs, and to inform the developers of Markdown Here of this.

**Comment by adam-p** [comment]
I'm going to close this. I'm 99% sure that Thunderbird will never get WebExtensions. If it seems otherwise in  the future, this can be re-opened.

**Comment by bbalet** [comment]
Thunderbird will get WebExtensions in a near future:

https://bugzilla.mozilla.org/show_bug.cgi?id=1396172
https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57
