### ISSUE TITLE
Markdown-Cheatsheet wiki titles are not displaying

### ISSUE THREAD

**Issue by poolebu** [adam-p/markdown-here#428]
The headers on the wiki are not displaying correctly, which in the header section is actually pretty funny :)

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lines.

**Comment by pleycpl** [comment]
Exactly, And these pages, 
https://github.com/adam-p/markdown-here/wiki/Compatibility
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet

And, Wiki Pages hasn't edit button, How to contribute these pages? Like this blog?
http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

**Comment by pleycpl** [comment]
According to these sites, I did something.
https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github/11481887
http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

Wiki Pages
https://github.com/pleycpl/markdown-here-wiki

**Comment by adam-p** [comment]
Fixed. Weird that this is broken:
```
<a blah />
## Header
```
But this isn't (the style I used on the [Tips & Tricks](https://github.com/adam-p/markdown-here/wiki/Tips-and-Tricks) page):
```
<a blah />
Header
======
```

@pleycpl : Sorry, I didn't pull your changes! I checked to see if there were any PR refs and then I started editing before reading your links.

**Comment by adam-p** [comment]
Oh, also: Yes, the wiki is locked for editing. For a while I was fixing defacement (or people trying out Markdown?) every second day.
