### ISSUE TITLE
Cannot open options/settings in Thunderbird

### ISSUE THREAD

**Issue by drjackyl** [adam-p/markdown-here#429]
I saw Issue #276 but as this issue has been resolved, I create a new issue describing the same problem, but probably with a different cause.

I cannot open the settings/options of the add-on in Thunderbrid's add-on-management.

Though, when I installed the add-on and restarted, the options opened automatically. The only way to re-open them is to remove the add-on with restart, reset the config-entries and re-install the add-on with restart.

I'm using Thunderbird v52.1.1 (64-Bit) on macOS 10.12.4 with Markdown Here v2.12.0 in German.

**Comment by smz** [comment]
Hello,

same problem here under Windows 8.1, Thunderbird 52.1.1 (32-bit), Markdown Here 2.12.0.

Click on "Options" (_from the main Add-ons Manager or from Markdown Here "more..." page_) and you're stuck: only way out is to kill Thunderbird.

The issue doesn't seems to be confined to MacOS...
