### ISSUE TITLE
how can I label equation with a symbol ,such as \tag{} in Tex ?

### ISSUE THREAD

**Issue by nikoong** [adam-p/markdown-here#431]
$equation \tag{1}$ can’t set a tag behind the equation. There is noting happened.

**Comment by adam-p** [comment]
Does it work here: https://www.codecogs.com/latex/eqneditor.php ...? (I don't know TeX and I have no idea what it should look like.)

**Comment by adam-p** [comment]
Closing. Re-open if there's more info.
