### ISSUE TITLE
Unavailable from Mozilla add-on store

### ISSUE THREAD

**Issue by et2010** [adam-p/markdown-here#432]
After reinstall my firefox, I want to install markdown-here from Mozilla add-on store but it's not there. I googled but there is little information. Anyone know what is going on? Thanks!

**Comment by adam-p** [comment]
With an existing Firefox installation, if you have extensions installed then Firefox's new multi-process mode is disabled. So your Firefox will work with legacy extensions (like the currently released Markdown Here). But when you do a reinstall, then multi-process mode will be enabled and you can't use legacy extensions without disabling it.

I recommend that you leave multi-process mode enabled and install the not-yet-fully-reviewed WebExtensions version of Markdown Here. Available from: https://addons.mozilla.org/en-US/firefox/addon/markdown-here/

Please close this issue if that works for you.

**Comment by et2010** [comment]
It works. Thanks!
