### ISSUE TITLE
Issues with v2.13.1

### ISSUE THREAD

**Issue by jrappen** [adam-p/markdown-here#434]
## v2.13.1 issues

* Installation on [Firefox](https://addons.mozilla.org/en-US/firefox/addon/markdown-here/versions/) fails
  * add-on unreviewed
* Installation on [Thunderbird](https://addons.mozilla.org/en-US/thunderbird/addon/markdown-here/versions/) works, however...
  * add-on unusable
    * button missing
    * context menu entry missing
    * keyboard shortcut doesn't work
  * options page
    * 4x the size of my screen and can't be resized
    * dropdowns don't work
    * text fields empty
* Installation on [Postbox](https://addons.mozilla.org/en-US/thunderbird/addon/markdown-here/versions/) fails
  * corrupt file reported

**Comment by adam-p** [comment]
How are you installing it? Via addons.mozilla.org? I don't intend for MDH to be installable from the Github Releases (unless there's a compelling reason why it should be). You can get the not-yet-reviewed signed version here: https://addons.mozilla.org/en-US/firefox/addon/markdown-here/

**Comment by adam-p** [comment]
...Also, if you're installing via that link: That's the WebExtensions version of MDH. Thunderbird doesn't support WebExtensions and probably never will. There will continue to be separate releases for it (one is coming up soon). (Someone created an issue to track when Tbird support WebExt, but I highly doubt it will ever make sense: #423)

Thunderbird/Postbox/Pale Moon/Ice Dove releases are available here: https://addons.mozilla.org/en-US/firefox/addon/markdown-here-xul/

Those download links are all here: http://markdown-here.com/get.html

**Comment by jrappen** [comment]
@adam-p

I was using the `markdown-here` add-on link, the old `markdown-here-xul` link works just fine.

The `markdown-here` link **does not include** the Thunderbird binaries. Compare:

* https://addons.mozilla.org/en-US/thunderbird/addon/markdown-here/versions/
  * Android
  * Firefox
* https://addons.mozilla.org/en-US/thunderbird/addon/markdown-here-xul/versions/
  * Firefox
  * Thunderbird

But you knew that..

---

⚠️ A side note: As a result <https://addons.mozilla.org/en-US/thunderbird/addon/markdown-here/> does redirect to <https://addons.mozilla.org/en-US/firefox/addon/markdown-here/versions/>.

**Comment by aphirst** [comment]
Is there an ETA on when 2.12.1 for Thunderbird will hit the Mozilla addons page, or is it simply "whenever they're done reviewing it"? I was keen to try it out due to the the inability to open the options menu (and thus, no syntax highlighting for me yet).

**Comment by adam-p** [comment]
Soon, soon. I'm "coordinating" with Mozilla, per: https://discourse.mozilla-community.org/t/best-way-to-split-thunderbird-and-firefox-users-because-webextensions/9717/5
