### ISSUE TITLE
Console Errors on Medium.com

### ISSUE THREAD

**Issue by lincoln-b** [adam-p/markdown-here#435]
I was watching the YouTube video on this page: https://hackernoon.com/the-new-chrome-devtool-feature-you-want-to-know-about-c0d2371151d6, and opened up my developer tools, only to behold a great swatch of uncaught DOMExceptions.

> Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://hackernoon.com" from accessing a cross-origin frame.
>     at Function.findFocusedElem (chrome-extension://elifhakcjgalahccnjkneoccemfahfoa/common/markdown-here.js:79:36)
>     at intervalCheck (chrome-extension://elifhakcjgalahccnjkneoccemfahfoa/chrome/contentscript.js:238:42)

![Console Screenshot: http://i.imgur.com/4XPDR1d.png](http://i.imgur.com/4XPDR1d.png "Console Errors")

Thought you'd like to know :)

**Comment by adam-p** [comment]
Will be fixed in next release. Thanks.

Related to #173.
