### ISSUE TITLE
Add &nbsp; and &8209; for non-breaking space and hyphen, respectively.

### ISSUE THREAD

**Issue by rebcabin** [adam-p/markdown-here#436]
I found these work in Jupyter notebooks.

**Comment by adam-p** [comment]
I don't understand what you're asking or suggesting. What do you mean by "add" them?

In case it's not clear, you can just use those entities in your Markdown and MDH will render them. Maybe that's what you want? (But make sure to use `&#8209;` and not `&8209;`.)

**Comment by adam-p** [comment]
Closing. Re-open if there's more info.
