### ISSUE TITLE
enhancement: send plain text, render on the fly

### ISSUE THREAD

**Issue by quantenschaum** [adam-p/markdown-here#439]
I prefer plain text mail, no HTML. It would be nice, if markdown-here rendered markdown (if detected) on the fly when viewing mails (received ones or those sent). The mails are transferred in plain text, which is perfectly readable with a text only client, but are displayed as rendered markdown.

**Comment by pprw** [comment]
+1 

Plain text are still the best way to exchange emails. It is a little pity that a email wrote in markdown would not be render properly if I open it with mutt (without html configuration).

Markdown here should enhance the way we read markdown (coloration?) but with an option to no convert it to html.

**Comment by adam-p** [comment]
Similar to #24 and #15. This is too much of a departure from Markdown Here. 

(It also has the downside of requiring that recipients have the extension installed. And won't work on extension-less mail readers, like the Gmail app.)

**Comment by quantenschaum** [comment]
Your decision. But in my and others opinion this feature made perfectly sense. MD is very readable in non-rendered form (a design feature of MD), so sending plain text non-rendered MD would be no problem.
