### ISSUE TITLE
Does it support the feature of ToC ( Table of Contents )?

### ISSUE THREAD

**Issue by HappyTreeFriend** [adam-p/markdown-here#442]
Does it support the feature of ToC ( Table of Contents )?

**Comment by adam-p** [comment]
There's no ToC auto-regenerate feature, but you can do it manually, like so:

```
##### Table of Contents  
[Header 1](#header1)  
[Header 2](#header2)  

<a name="header1"/>

## Header 1

...stuff here...

<a name="header2"/>

## Header 2

...stuff here...
```
(IIRC, those empty lines between anchors and headers are important.)

You can see that style of ToC in the [cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet).

ToC generation isn't standard Markdown, and MDH may never support it, but... it might. Going to close this, though.

**Comment by sheep-liu** [comment]
But when the content is complicated, it is hard to do it manually, like so:
![image](https://user-images.githubusercontent.com/52167840/141733619-0e6a6298-9bac-47f9-b14c-6793445a65a8.png)
