### ISSUE TITLE
Enhancement: Switch message font in Google Inbox

### ISSUE THREAD

**Issue by watkinsmatthewp** [adam-p/markdown-here#445]
I love Markdown Here. So much so that in Gmail, I changed my Gmail default font to Fixed Width to facilitate writing my emails in Markdown.

But I also love Google Inbox. And sadly, Google Inbox doesn't yet let you change your default font for your compose window. So I'm stuck writing my Markdown in variable-width Sans Serif font :(

It would be great to have an option on the Markdown Here settings that, if checked, will automatically select Fixed Width as my message font in Google Inbox when I compose a message or reply.

This is probably unrealistic, but it sure would be nice!

**Comment by adam-p** [comment]
I hear you, but no. This is out of scope for MDH. It would probably best be done with a dedicated browser extension.
