### ISSUE TITLE
Empty Table does not generate

### ISSUE THREAD

**Issue by cconmy** [adam-p/markdown-here#448]
When using extension within Chrome with WYSIWYG editors in ZenDesk Help Center or Gmail with a table.

If the very bottom right cell of a table is empty, the cell will not be displayed in the html table.

Example below.
```
| Severity |             Resolution Time             |                                    Note                                     |
|:--------:| --------------------------------------- | --------------------------------------------------------------------------- |
|    1     | By end of next half day                 | Resolution available 24 hours a day, 7 days a week.                         |
|    2     | By end of next business day or Saturday | Resolution available on business days and Saturday, 06:00 UTC to 23:00 UTC. |
|    3     | By end of next two business days        | Resolution available on business days, 06:00 UTC to 23:00 UTC.              |
|    4     | Not applicable                          |                                                                             |
```

**Comment by adam-p** [comment]
I don't have a suggestion. The MD example you gave works fine in Gmail, so I'm tempted to say that it's not MDH's problem. 

I don't have access to ZenDesk to test with. Maybe you can grab the HTML to see if it's looks wrong. Like so: https://github.com/adam-p/markdown-here/wiki/Troubleshooting#copying-html

Is it okay to work around it by putting a non-visible character in the cell? Like `&nbsp;`.

I'm closing this, but you can re-open if there's something we can reasonably do to fix it.
