### ISSUE TITLE
Problem with the Emphasis part in the Markdown Here Cheatsheet

### ISSUE THREAD

**Issue by aman5319** [adam-p/markdown-here#449]
Your cheatsheet says for 
Combined emphasis with **BoldItalics and _BoldItalics_** ,
this doesn.t work instead after lots of hit and trail i got the answer that is for both Bold and Italic one should use in the manner
_**BoldItalics**_

**Comment by adam-p** [comment]
I can't reproduce this. And your example in the issue above looks correct. And the cheatsheet render looks correct.

Both of these look right to me:
```
**_insideout_**
_**outsidein**_
```

They both work in Github:
**_insideout_**
_**outsidein**_

And they both work for me in Chrome+Gmail.

I'm closing this, but if you can provide more info we'll re-open and investigate.

**Comment by ViniciusBRodrigues** [comment]
Bold simply doesn't work for me. I have tried many web browsers.
