### ISSUE TITLE
Options not Getting Saved in Firefox

### ISSUE THREAD

**Issue by Waldovski** [adam-p/markdown-here#450]
MDH version: 2.13.1
Firefox version: ESR 52.3.0 (64bit)

When I change my options, I get the "Changes Saved" message on the right, but then I close and re-open and they're back to what they used to be.

**Comment by musse** [comment]
I have the same issue with the same versions.

**Comment by adam-p** [comment]
WebExtensions support wasn't complete by Firefox 53 ([e.g.](https://blog.mozilla.org/addons/2017/02/28/compatibility-for-firefox-53/)). 

I recommend using the legacy version of MDH until you can upgrade your browser.
https://addons.mozilla.org/en-US/firefox/addon/markdown-here-xul/
