### ISSUE TITLE
SOLVED:  Math not rendered on incoming mail

### ISSUE THREAD

**Issue by calchilo** [adam-p/markdown-here#452]
Using Thunderbird 52.2.1 (64 bit) on Ubuntu 16.04 and "Markdown Here" version 2.13.2.  Math rendering works during email composing, but sent mail does not come back w/ math rendering.  Thunderbird will not download math graphic. Here is the incoming mail source relevant to this problem:

```html
      <p style="margin: 0px 0px 1.2em ! important;">math:</p>
      <p style="margin: 0px 0px 1.2em ! important;"><img
          src="https://chart.googleapis.com/chart?cht=tx&amp;chl=E%3Dmc%5E2"
          alt="E=mc^2"></p>
```
I've checked my thunderbird preferences and don't see options preventing this file down load.

Jim Haefner

**Comment by tachim** [comment]
@calchilo what was the problem?
