### ISSUE TITLE
Line wrapping problem

### ISSUE THREAD

**Issue by chimit** [adam-p/markdown-here#455]
If you convert the last line of your text to markdown all new lines are wrapped by the same  markdown highlighting and you can't remove it:

![2017-10-05 15 38 47](https://user-images.githubusercontent.com/839349/31215741-5954489c-a976-11e7-8532-a01adb4caf6f.png)

![2017-10-05 15 40 26](https://user-images.githubusercontent.com/839349/31215790-914f1b32-a976-11e7-86d7-35933e46161f.png)

![2017-10-05 15 40 41](https://user-images.githubusercontent.com/839349/31215801-99d2b16a-a976-11e7-8a5f-497104fdaad8.png)

**Comment by adam-p** [comment]
There's nothing MDH can do about that. That just how rich editors work. 

Workaround: Unrender back to plaintext and do the editing.
