### ISSUE TITLE
xss in editor

### ISSUE THREAD

**Issue by Hackriderroot** [adam-p/markdown-here#464]
use this comment in editor will trigger the xss

[![onmouseover=prompt(1)]()](javascript:alert`1`;)

tested in the demopage :  http://markdown-here.com/livedemo.html

![mark_down xss](https://user-images.githubusercontent.com/32172465/32400159-c5923474-c122-11e7-9d98-abb031d27a07.png)

**Comment by adam-p** [comment]
Thanks for the report. It's fixed now on the website. 

The larger problem is that script should be stripped from Markdown when rendering (probably/surely). That will probably have to wait until switching to markdown-it as the rendering library. Anyway, it's fixed on markdown-here.com using CSP.

**Comment by Hackriderroot** [comment]
That's great :)
