### ISSUE TITLE
Repeated options page open on browser start

### ISSUE THREAD

**Issue by jaybosamiya** [adam-p/markdown-here#467]
I am on Debian Stretch, with Firefox 52.4.0 (64-bit).

Almost every time I open the browser, the options (`/common/options.html`) page opens automatically, and I am not sure why this is happening (nor is there an option to disable this).

Please do let me know what steps I could try to prevent this.

**Comment by gtackett** [comment]
This may be the same as [https://github.com/adam-p/markdown-here/issues/444](#444).

**Comment by jaybosamiya** [comment]
Yep, this is the same. Closing this.
