### ISSUE TITLE
v2.13.3 Does Not Work on Thuderbird v60.0

### ISSUE THREAD

**Issue by KSR-Yasuda** [adam-p/markdown-here#524]
The latest update of Markdown Here (to v2.13.3),
it has come not to work on Thunderbird v60.
I wonder they say it supports v60 (https://github.com/adam-p/markdown-here/issues/495)...

* In mail edit window:
    * It does not respond to keyboard shortcut (Ctrl + Shift + M)
    * No Markdown Here button can be added to toolbar (Such button does not exist)
* In main window:
    * It can open Markdown Here addon setting page

Also, on Thunderbird v52,
Markdown Here looks not working in mail edit window, same as Thunderbird v60.

Re-installed Markdown Here addon and Thunderbird, however, it does not get well.

I'm quite at a loss as it does not work on any ver. of Thunderbird... X'(

#### Environment

* Markdown Here 2.13.3
* Thunderbird 60.0 (32bit)
* Windows 8.1 Pro (64bit)

**Comment by ensleep** [comment]
Environment
Markdown Here 2.13.3
Thunderbird 60.0 (32bit)
Windows 10 Pro (64bit)

Does not work too!

**Comment by pmanu93** [comment]
Same... After the update I'm unable to use the addon

**Environment**
 - Markdown Here 2.13.3;
 - Thunderbird 60.0b11 (64 bits);
 - Linux Mint 17.3 (64 bits)

**Comment by stombi** [comment]
Same issue as original post (also tested with fresh install and new profile)

Environment
- Markdown Here 2.13.3
- Thunderbird 60.0 (64 bits)
- Linux Debian 8.11 (64 bits)

**Comment by adam-p** [comment]
Things to try:
1. If you right-click in the message compose box, do you have the MDH context menu item? Does it work?
2. Open the MDH options and try setting the hotkey to something else. Maybe Ctrl+Shift+M is specifically problematic.

**Comment by stombi** [comment]
- there is no context menu item
- tried any combination of Alt / Ctrl / Shift / key (with TB restart each time) 

it still doesn't work

**Comment by KSR-Yasuda** [comment]
Neither does my environment:

> 1. If you right-click in the message compose box, do you have the MDH context menu item? Does it work?

No context menu of MDH exists.

> 2. Open the MDH options and try setting the hotkey to something else. Maybe Ctrl+Shift+M is specifically problematic.

Changed, but it does not respond, either.

It looks MDH add-on is completely not working, but MDH add-on option page.

For now, I anyway rolled back to [MDH v2.13.2] and [Thunderbird v52.9.1]...

[Thunderbird v52.9.1]: https://ftp.mozilla.org/pub/thunderbird/releases/52.9.1/win32/ja/
[MDH v2.13.2]:         https://addons.thunderbird.net/en-us/thunderbird/addon/markdown-here-xul/versions/?page=1#version-2.13.2

**Comment by littdky** [comment]
Does not work too!

**Environment**

- Markdown Here 2.13.3
- Thunderbird 60.0 (32bit)
- Windows 10 Pro (64bit)

**Comment by adam-p** [comment]
@stombi : Thanks for this clue:
> edit : context menu item and then transform to markdown works with Thunderbird en_US , my Thunderbird is fr_FR I think

Does everyone else use a non-English Thunderbird UI? I've reproduced the problem when using a different language.

**Comment by adam-p** [comment]
Mozilla approved the new version just now. You should get the update automatically, or you can down it from here: https://addons.thunderbird.net/en-US/thunderbird/addon/markdown-here-xul/versions/

**Comment by KSR-Yasuda** [comment]
Now it goes well with v2.13.4. Thank you!

> Does everyone else use a non-English Thunderbird UI?

Yes, mine is non-English, too (Japanese).
So, that was it, huh?
