### ISSUE TITLE
matrix latex failed in markdown-here

### ISSUE THREAD

**Issue by dengfei2013** [adam-p/markdown-here#573]
I find markdown-here support the formula:

$\frac{x+3}{1-y^2}$

It worked well, but when I use matrx latex, It didn't work:

Here is my formula code:

```
$$ \begin{bmatrix} u\\e \end{bmatrix}  \sim 
N (\begin{bmatrix}0\\0\end{bmatrix},
\begin{bmatrix} G(\sigma_g) &0\\ 0 &R(\sigma_{\gamma})\end{bmatrix})$$
```

**Comment by cben** [comment]
This is a simple syntax issue: If you remove the space between opening `$$` and `\begin{bmatrix}`, it works.
```
$\begin{bmatrix} u\\e \end{bmatrix}  \sim 
N (\begin{bmatrix}0\\0\end{bmatrix},
\begin{bmatrix} G(\sigma_g) &0\\ 0 &R(\sigma_{\gamma})\end{bmatrix})$
```

Note also that you don't need double dollar; MDH doesn't have separate `$$` vs `$` syntax, and if you write `$$` you'll currently simply get extra dollars around the rendered formula.(https://github.com/adam-p/markdown-here/issues/231).
