### ISSUE TITLE
Markdown Here is not installing on Thunderbird 68.7.0

### ISSUE THREAD

**Issue by morozdan2003** [adam-p/markdown-here#612]
I have tried to install versions from [Mozilla Addons Store](https://addons.mozilla.org), from Releases tab on this GitHub repository. It seems like extension is incompatible with that version of Thunderbird.

**Comment by ReekyMarko** [comment]
Duplicate of #577
TLDR; This addon is abandoned. Last commit in this repo is from 2018.
