### ISSUE TITLE
404 error: Link not working 

### ISSUE THREAD

**Issue by Aurum1611** [adam-p/markdown-here#617]
http://softwaremaniacs.org/media/soft/highlight/test.html is not working. This link is present in the code highlighting section which is supposed to be a guide to all the different types of languages that can be used for code highlighting and how to write their names.

**Comment by GITHUB-USER-0** [comment]
Seems possible that the link has been moved to the following location: [https://softwaremaniacs.org/media/blog/highlighters/highlight.js/test.html](https://softwaremaniacs.org/media/blog/highlighters/highlight.js/test.html)
