### ISSUE TITLE
Math is now 404

### ISSUE THREAD

**Issue by Artoria2e5** [adam-p/markdown-here#864]
When trying to figure out #699 I discovered that math is now 404:
![image](https://github.com/user-attachments/assets/3d3620a9-1b10-4b5e-9b6c-508ace02edf8)

Maybe using an external service to render the TeX wasn't such a good idea after all... What are the chances we can use KaTeX HTML/CSS output for this?

### Implementation sketch

* Link to katex.min.css to output *if* formula exists. Now linking to an external CSS is really silly for an e-mail, but https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css makes extensive references to fonts and other assets, and we are never getting them all.
* For each formula block, call `katex.renderToString()` on it and paste in the resulting HTML. If the block is *not* inline, add `{ displayMode: true }`.

### Other ideas

Run mathjax and paste the SVG in -- possibly cheaper than getting the CSS, now that I think about it! Run `MathJax.tex2svg()` on the string, be sure to respect the inline-ness and set `{ display: false }` if the block *is* inline.

**Comment by gtusr** [comment]
[TeXSend-Gmail](https://github.com/LoganJFisher/TeXSend) userscript works quite well with Markdown Here in Gmail ... so maybe it can be integrated directly into the MHD extension as an additional option.
